synthetichealth/synthea_java

src/main/java/org/mitre/synthea/modules/State.java
SetAttribute states are allowed to exclude the "value" field, in which case the corresponding attribute should be null. Currently if one of these states is hit it causes a NullPointerException at `definition.get("value")`.
=> Fix NPE on SetAttribute states with no value

src/main/java/App.java, src/main/java/org/mitre/synthea/helpers/RandomCollection.java, src/main/java/org/mitre/synthea/modules/Generator.java, src/main/java/org/mitre/synthea/modules/LifecycleModule.java, src/main/java/org/mitre/synthea/modules/Person.java, src/main/java/org/mitre/synthea/world/Demographics.java, src/main/java/org/mitre/synthea/world/Location.java, src/main/resources/synthea.properties, src/test/java/org/mitre/synthea/modules/GeneratorTest.java
Synthetic population now roughly aligns to real-world demographics, based on selected config json.
By default the generated population is based on the full state of MA, using towns.json, but this is configurable.
This is not quite as robust as the ruby version yet, because I think there are still some wrinkles to iron out w.r.t person seeds. I.e., in the ruby version we select target demographics to ensure that the right number of people fall into each bucket, and if a person dies we start over. Here we need to ensure that a person seed always generates the same person, so we need to figure out how to combine those 2 ideas.
=> Add demographics, using city + town json config

src/main/java/org/mitre/synthea/export/FhirStu3.java, src/main/java/org/mitre/synthea/helpers/QualityOfLife.java, src/main/java/org/mitre/synthea/modules/Generator.java, src/main/java/org/mitre/synthea/modules/State.java, src/main/resources/gbd_disability_weights.json, src/test/java/org/mitre/synthea/modules/QualityOfLifeTest.java
This PR introduces calculations for DALYs (disability adjusted life years) and QALYs (quality adjusted life years) for patients.  Disability weights are taken from the Global Burden of Disease Study 2015 (http://ghdx.healthdata.org/gbd-2015) and are used to calculate DALY.  These disability weights are mapped to conditions using SNOMED codes and stored in `resources/gbd_disability_weights.json`. 
DALY is calculated on a yearly timestep, after the patient has been generate, by `QualityOfLife.java`.  The calculate method takes `stop` as an argument, which is the time during a patient’s life that the quality of life values should be calculated.  This value is currently set to the end of the simulation.  
> Disability-Adjusted Life Year = DALY = YLL + YLD
>  Years of Life Lost = YLL = (1) * …
=> Quality of life

src/main/java/org/mitre/synthea/modules/CardiovascularDiseaseModule.java, src/main/java/org/mitre/synthea/modules/EncounterModule.java, src/main/java/org/mitre/synthea/modules/Generator.java, src/main/java/org/mitre/synthea/modules/HealthRecord.java, src/main/java/org/mitre/synthea/modules/LifecycleModule.java, src/main/java/org/mitre/synthea/modules/Module.java, src/main/java/org/mitre/synthea/modules/Person.java, src/main/java/org/mitre/synthea/modules/State.java, src/main/java/org/mitre/synthea/modules/VitalSign.java
Reworks wellness encounters so they are properly scheduled and only fire once per module (so the wellness encounter and med_rec modules don't endlessly loop).
Vital sign skeleton is also here. Until this is fully implemented, the observations have null values.
=> Fix wellness encounters and skeleton vital signs.

src/main/java/org/mitre/synthea/modules/CardiovascularDiseaseModule.java, src/main/java/org/mitre/synthea/modules/EncounterModule.java, src/main/java/org/mitre/synthea/modules/EventList.java, src/main/java/org/mitre/synthea/modules/LifecycleModule.java, src/main/java/org/mitre/synthea/modules/Person.java, src/main/java/org/mitre/synthea/modules/State.java
Ports the cardiovascular disease module from Ruby to Java. This is intended to only be a stop-gap measure until we have time to convert the CVD module to GMF, which would be a much larger endeavor, so this is intentionally left kind of rough. Many of the names use ruby naming conventions instead of java naming conventions because they were copy & pasted from ruby code, and left that way so that it's easier to trace back to the ruby origins.
=> Cardiovascular disease module

src/main/java/org/mitre/synthea/modules/CommunityHealthWorker.java, src/main/java/org/mitre/synthea/modules/Generator.java, src/main/java/org/mitre/synthea/modules/HealthRecord.java, src/main/java/org/mitre/synthea/modules/LifecycleModule.java, src/main/java/org/mitre/synthea/modules/Person.java, src/main/java/org/mitre/synthea/modules/State.java, src/main/java/org/mitre/synthea/world/Location.java, src/main/resources/synthea.properties
* Initial implementation of community health workers (minimum viable product) into the Synthea java implementation 
* Community health workers provide 15 preventive services defined by the USPSTF 
* Community health workers have a location, cost, and accompanying budget information
Each community health worker is mapped to a service and city. For now, all community health workers provide all 15 preventive services. An additional service named "organize" was also discussed as being a measure of social support in the community provided by the community health worker, and can be implemented/defined later on. Community health workers are assigned a city at random, and the cost per community health worker is set in the Synthea properties file. Budget inputs, also in the Synthea properties …
=> Community Health Workers

src/main/java/org/mitre/synthea/export/FhirStu3.java, src/main/java/org/mitre/synthea/modules/Generator.java, src/main/java/org/mitre/synthea/modules/Module.java, src/main/java/org/mitre/synthea/modules/QualityOfLifeModule.java, src/test/java/org/mitre/synthea/modules/QualityOfLifeTest.java
Migrates the Quality of Life calculations (QALY/DALY) to a module so that a person's QALY and DALY are calculated every year. This works by storing the QALY/DALY history in an array, where the array index is their age. When the patient is exported, only the most recent QALY/DALY is written to the FHIR record. (Same as today)
This will be necessary to track QALY/DALY values of a population over time
=> Migrate quality of life to a module so QALY/DALY are calculated every year

src/main/java/org/mitre/synthea/modules/HealthInsuranceModule.java, src/main/java/org/mitre/synthea/modules/Module.java, src/main/resources/synthea.properties
Medicaid eligibility: `blind || pregnant || (income <= 1.33 * poverty_level)`
Medicare eligibility: `65 or older || ESRD`
Private insurance: It's complicated. Basically, before individual or employer mandates became law, you got insurance if you have a high income (here we also use that interchangeably as a placeholder for a good job that provides insurance). After individual mandates, you get insurance if you have employment at a business with more than 50 people (I've arbitrarily translated that roughly to an `occupation_level >= 0.2`). (Wikipedia employer mandates https://en.wikipedia.org/wiki/Health_insurance_mandate#Employer_mandates).
As a child, your income and occupation (set randomly at birth) act as a proxy for your parent's income.
If you've slipped through all of these cracks, …
=> Add insurance: none, private, medicaid, medicare, dual.

src/main/java/org/mitre/synthea/modules/Module.java, src/main/java/org/mitre/synthea/modules/State.java
String.format is slower than using StringBuilder to concatenate strings (some sources say 100x slower). Not a big deal on things we don't call often, but I profiled the code and the String.format call in Module.process accounted for nearly 20% of app runtime. There are probably a lot of additional performance improvements, but this one is basically free.
=> Replace 2 instances of String.format with implicit stringbuilder for performance

src/main/java/App.java, src/main/java/org/mitre/synthea/modules/CommunityHealthWorker.java, src/main/java/org/mitre/synthea/modules/Immunizations.java, src/main/java/org/mitre/synthea/modules/Person.java, src/main/resources/synthea.properties
The 15 preventive services, as outlined by the USPSTF, can each be provided by community health workers. The goal is for the user to determine which of the services are provided by community health workers. Additionally, conditions for the "quit smoking" and quit alcoholism" methods are added to determine if tobacco screening or alcohol counseling services are provided by the community health worker.
=> Set CHW preventive services

build.gradle, src/main/java/org/mitre/synthea/datastore/DataStore.java, src/main/java/org/mitre/synthea/export/HospitalExporter.java, src/main/java/org/mitre/synthea/modules/CardiovascularDiseaseModule.java, src/main/java/org/mitre/synthea/modules/EncounterModule.java, src/main/java/org/mitre/synthea/modules/Generator.java, src/main/java/org/mitre/synthea/modules/State.java, src/main/java/org/mitre/synthea/world/Provider.java
Updates the Provider-based utilization numbers to be tracked on a yearly basis instead of all in 1 bucket.
Now instead of a Map of Type -> Count, it's a 2D map/Table of (Year,Type) -> Count. Uses the Google Guava library for Table:  https://github.com/google/guava/wiki/NewCollectionTypesExplained#table 
Also expands the keys to track all encounters, as well as encounters grouped by class.
Also reworked the FHIR hospital exporter a little bit - previously it was converting the bundle to a JSON string after every iteration of the loop, now it only converts after all hospitals have been added to the bundle.
=> Rework Utilization to be tracked by year

src/main/java/org/mitre/synthea/modules/CardiovascularDiseaseModule.java
Fix an if/else where the contents of the blocks were reversed. If a number is greater than or equal to the size of a list/array, it should not be used as an array index. This bug probably also had the effect of making strokes far more likely than usual.
=> Fix reversed if/else

src/main/java/org/mitre/synthea/datastore/DataStore.java, src/main/java/org/mitre/synthea/export/Exporter.java, src/main/java/org/mitre/synthea/export/HospitalExporter.java, src/main/java/org/mitre/synthea/export/ReportExporter.java, src/main/java/org/mitre/synthea/helpers/Config.java, src/main/java/org/mitre/synthea/modules/CommunityHealthWorker.java, src/main/java/org/mitre/synthea/modules/Generator.java, src/main/java/org/mitre/synthea/modules/Person.java, src/main/java/org/mitre/synthea/world/Location.java, src/main/java/org/mitre/synthea/world/Provider.java, src/main/resources/synthea.properties
Adds a Report exporter, to generate a "report" in JSON format containing info on the previous run of synthea, specifically including access, outcomes, and cost, as well as the config parameters that produced these results. Cost isn't in synthea yet but we have # of encounters for access, and QOL info for outcomes.
Sample report: 
[statistics-2017-09-11_09-25-19.json.txt](https://github.com/synthetichealth/synthea_java/files/1292676/statistics-2017-09-11_09-25-19.json.txt)
This report format will likely be iterated on multiple times before being finalized, but I wanted to get something in the repo asap.
Also, reworks the CommunityHealthWorker class to be a subclass of Provider, making it easier to track utilization.
=> Report exporter

src/main/java/org/mitre/synthea/modules/CommunityHealthWorker.java, src/main/java/org/mitre/synthea/modules/LifecycleModule.java, src/main/java/org/mitre/synthea/modules/Person.java, src/main/java/org/mitre/synthea/modules/State.java, src/main/resources/modules/lung_cancer.json
Updates the Lung Cancer module to take into account lung cancer screening interventions.
CHW encounter performs a Low-dost CT scan if they offer the service and the patient meets the necessary criteria.
The Lung Cancer module is updated so that the screening will affect the stage of cancer the person has when they start treatment. This is accomplished by adding a counter to the start of the module, counting the duration of how long the person has undetected lung cancer. This loop can either be broken out of randomly, or if they get the screening provided by a CHW.
The numbers will likely need to be tweaked but this is a first pass.
Updated module image:
=> Lung cancer intervention

src/main/java/org/mitre/synthea/modules/CardiovascularDiseaseModule.java
There's a bug in the CardiovascularDiseaseModule where patients are prescribed medications dozens of times. Just a copy&paste issue - the `prescribeMedication` method is supposed to add a medication to a list to be prescribed, if they aren't already taking it, and the `stopMedication` method is supposed to add a medication to a list to be ended, if they **are** already taking it.
=> Fix bug causing excessive CVD medications

src/main/java/org/mitre/synthea/datastore/DataStore.java
Replaces the location of the DB file from the user's home directory to a project-relative location within the synthea_java project folder. If you have synthea_java in your home directory this change has no effect.
=> Use project-relative location for DB file

src/main/java/org/mitre/synthea/modules/CommunityHealthWorker.java, src/main/resources/synthea.properties
Add a config setting to change when Community Health Workers are introduced into the system. Default setting is 1900 to mean "CHWs always available"
(branch name should be chw_year_introduced not cvd, whoops)
=> Add CHW introduction year config setting

src/main/java/org/mitre/synthea/modules/CommunityHealthWorker.java, src/main/java/org/mitre/synthea/modules/HealthRecord.java, src/main/java/org/mitre/synthea/modules/LifecycleModule.java, src/main/resources/modules/injuries.json
Adds screenings related to the Injuries model and osteoporosis. Specifically this includes:
- Osteoporosis screening: women 
- The USPSTF recommends screening for osteoporosis in women age 65 years and older and in younger women whose fracture risk is equal to or greater than that of a 65-year-old white woman who has no additional risk factors. 
- Falls prevention in older adults: exercise or physical therapy 
- The USPSTF recommends exercise or physical therapy to prevent falls in community-dwelling adults age 65 years and older who are at increased risk for falls. 
- Falls prevention in older adults: vitamin D 
- The USPSTF recommends vitamin D supplementation to prevent falls in community-dwelling adults age 65 years and older who are at increased risk for falls. 
The impacts of these …
=> Injuries screenings

build.gradle, src/main/java/Graphviz.java
Clones the Graphviz export from the ruby version of Synthea. Run this with the gradle task 'graphviz', for example `./gradlew graphviz`. Files are export to the default export folder.
Note that this uses a pure Java impl of Graphviz so it is slower than a native version, but adds no system-level dependencies. Suggestions to improve performance include adding the ability to specify only a single module to generate an image for, or track file modification times to only regenerate images where the corresponding module has changed since the last generation.
Sample images (they are largely the same as the ruby versions but not exactly identical -- some of the spacing is a little different)
=> Add graphviz export

src/main/java/org/mitre/synthea/engine/State.java, src/main/java/org/mitre/synthea/modules/CardiovascularDiseaseModule.java, src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java, src/test/java/org/mitre/synthea/engine/LogicTest.java, src/test/java/org/mitre/synthea/engine/StateTest.java
Updates all `reason`s in HealthRecord.Entry classes to be Codes instead of Strings. This means that the relevant information is directly accessible and doesn't have to be looked up in arbitrary places.
=> Change reasons from Strings to Codes

src/main/java/org/mitre/synthea/export/CSVExporter.java, src/main/java/org/mitre/synthea/world/geography/Location.java, src/test/java/org/mitre/synthea/helpers/TransitionMetricsTest.java
Location.getZipCode() now actually returns the zip code for a city, rather than 00000. It uses the patient's source of randomness to pick a random value if there's more than one zip code for a city, so one of the unit tests had to have a seed change to still see the expected results.
Also I noticed the CSV file didn't have full addresses like the Ruby version, it just had street address, so I added the city, state, and zip to patients.csv. Sample attached:
[patients.csv.txt](https://github.com/synthetichealth/synthea_java/files/1482394/patients.csv.txt)
=> Zip code & CSV fix

src/main/java/org/mitre/synthea/modules/LifecycleModule.java, src/main/resources/synthea.properties, src/test/java/org/mitre/synthea/helpers/TransitionMetricsTest.java
Adds 1-3 random numbers to the end of people's names, to make them more obviously fake. Unlike the ruby version which uses a few characters from the hash of the string, this just picks a random number between 0-999. (Is there a reason we would need all people with the same name to get the same number?)
This setting is configurable, `generate.append_numbers_to_person_names` , enabled by default.
Examples with it enabled:
> 6 -- Dovie291 Bauch348 (13 y/o) Framingham 
> 4 -- Ashlee792 Kling333 (8 y/o) Acton 
> 2 -- Allie427 Kovacek502 (24 y/o) North Andover 
> 1 -- Royce613 Stroman567 (21 y/o) Whitman 
> 3 -- Joaquin191 Feil113 (49 y/o) Newton 
> 10 -- Virginie157 Ratke350 (15 y/o) Franklin 
Examples with it disabled:
> 6 -- Ramona Koepp (45 y/o) Kingston 
> 4 -- Dena Waters (26 y/o) …
=> Add numbers to names

build.gradle
The way the `cleanOutput` task is defined it currently runs before every task, ex if you `gradle run` and then `gradle test`, it will delete all the output files from the run.
This change updates the task so it only runs when specifically called, ex `gradle cleanOutput`
=> Update cleanOutput task so it doesn't run before every task

build.gradle, src/main/java/org/mitre/synthea/engine/Module.java, src/main/java/org/mitre/synthea/engine/State.java, src/test/java/org/mitre/synthea/engine/StateTest.java
Modifies the CallSubmodule state so that the history of a submodule is added to the history of the calling module, as is currently done in the Ruby version. This should be preserved even if the submodule delays across multiple timesteps.
=> Submodule history added to calling module history

src/main/java/org/mitre/synthea/export/FhirStu3.java, src/main/java/org/mitre/synthea/export/PrevalenceReport.java, src/main/java/org/mitre/synthea/helpers/Utilities.java, src/main/java/org/mitre/synthea/modules/Immunizations.java, src/main/java/org/mitre/synthea/modules/LifecycleModule.java, src/main/java/org/mitre/synthea/modules/QualityOfLifeModule.java, src/main/java/org/mitre/synthea/world/agents/Hospital.java, src/main/java/org/mitre/synthea/world/concepts/BillingConcept.java, src/main/java/org/mitre/synthea/world/concepts/BiometricsConfig.java, src/main/java/org/mitre/synthea/world/concepts/GeographicalPracticeCostIndex.java, src/main/java/org/mitre/synthea/world/concepts/RelativeValueUnit.java, src/main/java/org/mitre/synthea/world/geography/Demographics.java, src/main/java/org/mitre/synthea/world/geography/Location.java, src/main/resources/synthea.properties
Currently files in src/main/resources get read into a String using an awful copy&pasted code snippet that looks like this:
```
InputStream stream = FhirStu3.class.getResourceAsStream(filename);
String json = new BufferedReader(new InputStreamReader(stream)).lines().parallel()
.collect(Collectors.joining("\n"));
```
This is awful and exists in too many places so I added a helper method Utilities.readResource() which takes a filename and returns the content of the file as a String.
=> Replace resource reading with a helper method

build.gradle, src/main/java/Concepts.java, src/main/java/org/mitre/synthea/helpers/Concepts.java, src/main/java/org/mitre/synthea/modules/CardiovascularDiseaseModule.java, src/main/java/org/mitre/synthea/modules/DeathModule.java, src/main/java/org/mitre/synthea/modules/EncounterModule.java, src/main/java/org/mitre/synthea/modules/Immunizations.java, src/main/java/org/mitre/synthea/modules/LifecycleModule.java, src/test/java/org/mitre/synthea/helpers/ConceptsTest.java
Catalog all codes & concepts into a CSV file. Runnable using `./gradlew concepts`.
This is a clone of the Ruby version, which scans through the JSON modules to find codes. For the few Java modules we have there's a new method to get all the codes used. It's not perfect for the Java modules but I don't want to recreate the shared "LOOKUP" from the ruby version.
Sample file is attached:
[concepts.csv.txt](https://github.com/synthetichealth/synthea_java/files/1521665/concepts.csv.txt)
=> Concept inventory

src/main/java/org/mitre/synthea/engine/Generator.java, src/main/java/org/mitre/synthea/export/Exporter.java, src/main/resources/synthea.properties, src/test/java/org/mitre/synthea/export/ExporterTest.java
Filters records for exporting, by keeping only the most recent 10 years of history (configurable). This is intended to mirror real health records which are frequently missing data.
Filtering is performed as follows:
- keep entries that are currently active (no end date)
- keep entries that were active at any point within the past 10 years (ie, end date is less than 10 years ago)
- delete encounters that are "empty" (no conditions, procedures, etc) and older than 10 years
- keep "cause of death" and related codes even if > 10 yrs old
This version is "destructive" in the sense that the entries are deleted from the record itself. As long as the export process is the last thing done to the Person object, this should have no negative impact.
=> Export filtering, destructive version

src/main/java/org/mitre/synthea/world/concepts/Costs.java
Offline feedback on the "remove_costs" PR mentioned the fact that the Ruby version left some default costs in, but the Java version only left 0.0. This change adds those same defaults to the Java version
=> Copy default costs from the ruby version

src/main/java/org/mitre/synthea/engine/Module.java, src/main/java/org/mitre/synthea/engine/State.java, src/test/java/org/mitre/synthea/engine/StateTest.java
Adds "time rewinding" so that delay states that expire between time steps lead to the next state at the correct time. For example, if a delay state is entered 1/1 and has a delay of 3 days, at the next timestep it will be 1/8, so we rewind time to 1/4 and enter the next state on 1/4 instead of 1/8.
A minor note is that CallSubmodule states need to be re-added to history when they complete for things to work out correctly.
=> Time Rewinding

src/main/java/org/mitre/synthea/engine/Generator.java, src/main/resources/synthea.properties, src/test/java/org/mitre/synthea/engine/GeneratorTest.java
Adds an "only dead patients" config setting, (disabled by default) which flips the generation logic such that only dead patients are exported and reported. The normal process still runs and produces "living" patients, but if this setting is enabled then those living patients are simply discarded, and another patient is generated to try to get a dead one. There should be no noticeable change to normal execution, where both living and dead patients are exported.
Note that this setting may significantly increase runtime for large patient cohorts because on average only about 1 in 5 generated patients dies.
Sample output with the setting disabled (normal usage):
```
4 -- Alvera113 Nicolas769 (18 y/o) Boston
1 -- Luciano237 Willms744 (90 y/o) Pepperell DECEASED
3 -- Athena83 Dibbert990 (46 …
```
=> Only Dead Patients config setting
